services:
  deno:
    image: denoland/deno:2.0.2
    working_dir: /project
    volumes:
      - .:/project
    tty: true
    environment:
      TZ: Asia/Tokyo
    ports:
      - 5173:5173
    command: ["deno", "task", "dev", "--host"]
